@startuml
!pragma layout smetana

object system
object menu
object user
object searchEngine
object media
object series
object movie
object category
object mediaLibrary

system *-- menu
system *-- user
system *-- mediaLibrary
mediaLibrary*--- media
mediaLibrary *-- searchEngine

media<|-- series
media<|-- movie
media*-- category





@enduml
